import type { Metadata } from "next";
import "./globals.css";
import { ContentProvider } from "../contexts/LocaleContext";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Welcome",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ContentProvider>
          <Theme>{children}</Theme>
        </ContentProvider>
      </body>
    </html>
  );
}
